### ISSUE TITLE
remove hardcoded docker org from the Dockerfile

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/zfs-localpv#213]
**Describe the problem/challenge you have**

We can remove the hardcoded docker org from the repo and add that as ENV which can be configured. This will help the people who has forked the repo. They can just set the env in the travis and image will be generated in that org.

**Describe the solution you'd like**

We can do similar thing we did in https://github.com/openebs/cstor-operators/pull/85/files

**Comment by codegagan** [comment]
I am looking into this.

**Comment by codegagan** [comment]
@pawanpraka1 I think this issue is already fixed with commit https://github.com/openebs/zfs-localpv/commit/a8a490e9cb0fa51b36226347b2bcdffa673fd433 and changes are present in master, and this issue can be closed.

https://github.com/openebs/zfs-localpv/blob/55a155c4a545fd2d46635662d86f6321d2eb115f/Makefile#L231 

https://github.com/openebs/zfs-localpv/blob/55a155c4a545fd2d46635662d86f6321d2eb115f/buildscripts/zfs-driver/Dockerfile#L35

**Comment by pawanpraka1** [comment]
that's right @codegagan. Thanks. Closing this issue.
