### ISSUE TITLE
Microk8s single node does not register CSI driver

### ISSUE THREAD

**Issue by dude051** [openebs/zfs-localpv#235]
**What steps did you take and what happened:**
Installed a fresh latest version of MicroK8s and followed instructions to do a standard install of zfs-localpv using:
https://openebs.github.io/charts/zfs-operator.yaml

One modification was made to up date `pods-mount-dir` to `/var/snap/microk8s/common/var/lib/kubelet` for MicroK8s.

After doing this all PVC's are left pending with:
``` 
Type     Reason                Age                From                                                                              Message
  ----     ------                ----               ----                                                                              -------
  Normal   ExternalProvisioning  10s (x4 over 33s)  persistentvolume-controller                                                       waiting for a volume to be created, either by external provisioner "zfs.csi.openebs.io" or manually created by system administrator
  Normal   Provisioning          4s (x6 over 33s)   zfs.csi.openebs.io_openebs-zfs-controller-0_80cb4fa8-989a-4039-b7e9-278b5d49ec97  External provisioner is provisioning volume for claim "services/pihole"
  Warning  ProvisioningFailed    4s (x6 over 33s)   zfs.csi.openebs.io_openebs-zfs-controller-0_80cb4fa8-989a-4039-b7e9-278b5d49ec97  failed to provision volume with StorageClass "openebs-zfs": rpc error: code = Internal desc = rpc error: code = Internal desc = scheduler failed
```

Further investigation reveals that the CSInode is not registering the driver to the node. If I set topology to force this via hostname, it does select the node and registers successfully.

**What did you expect to happen:**
I expect not having to enter topology information to provision resources. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-zfs-controller-0 -n kube-system -c openebs-zfs-plugin`
https://gist.github.com/dude051/334b71b592b24e6f5c1ba3c2d638c590
* `kubectl logs -f openebs-zfs-node-[xxxx] -n kube-system -c openebs-zfs-plugin`
https://gist.github.com/dude051/c19bc4b6a7f130bbf45ff817c671be7e
* `kubectl get pods -n kube-system`
```
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-86f78bb79c-zr7sk                1/1     Running   0          40h
openebs-zfs-controller-0                5/5     Running   0          19h
openebs-zfs-node-r4mvv                  2/2     Running   0          19h
```
* `kubectl get zv -A -o yaml`
```
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Anything else you would like to add:**
Zero drivers are registered:
```
kubectl get csinodes
NAME     DRIVERS   AGE
ubuntu   0         40h
```

```
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
...
  name: ubuntu
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: ubuntu
    uid: 74c27b54-4664-402a-b85d-8eb455970bd7
...
spec:
  drivers: null
```

Relavant logs for openebs-zfs-plugin on controller indicates it fails to find any topology informaton:
```
E1110 18:30:26.284588       1 scheduler.go:110] scheduler: topology information not provided
E1110 18:30:26.284674       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = rpc error: code = Internal desc = scheduler failed
```

If I set topology information for the hostname of the node, I get the driver to register and both a PVC is claimed and PV is bound. From what I have gathered this should not be required and it would make my deployments a lot easier with less modifications if I don't have to set this since once a PV is bound with the topology I then have to set affinity in my helm charts and deployments to match.

**Environment:**
- ZFS-LocalPV version: v1.0.1
- Kubernetes version (use `kubectl version`): v1.19.2
- Kubernetes installer & version: MicroK8s v1.19
- Cloud provider or hardware configuration: Baremetal single server
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1 LTS

**Comment by pawanpraka1** [comment]
@dude051 csi driver's registration seems to be failing. can you share the csi-driver-registrar container log from the openebs-zfs-node-r4mvv pod?

**Comment by dude051** [comment]
Thanks @pawanpraka1 I checked these logs and found nothing after the server starts but a `GRPC error`:

```
I1109 22:42:20.182279       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I1109 22:42:20.182380       1 main.go:120] Attempting to open a gRPC connection with: "/plugin/csi.sock"
I1109 22:42:20.182488       1 connection.go:151] Connecting to unix:///plugin/csi.sock
I1109 22:42:23.403414       1 main.go:127] Calling CSI driver to discover driver name
I1109 22:42:23.403549       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1109 22:42:23.403567       1 connection.go:181] GRPC request: {}
I1109 22:42:23.417617       1 connection.go:183] GRPC response: {"name":"zfs.csi.openebs.io","vendor_version":"v1.0.1"}
I1109 22:42:23.418968       1 connection.go:184] GRPC error: <nil>
I1109 22:42:23.418987       1 main.go:137] CSI driver name: "zfs.csi.openebs.io"
I1109 22:42:23.419256       1 node_register.go:58] Starting Registration Server at: /registration/zfs.csi.openebs.io-reg.sock
I1109 22:42:23.419887       1 node_register.go:67] Registration Server started at: /registration/zfs.csi.openebs.io-reg.sock
```

**Comment by pawanpraka1** [comment]
@dude051 is above the full log? I am looking for this `I1111 05:31:26.003126       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}` in the log.

```
I1111 05:31:24.480110       1 node_register.go:58] Starting Registration Server at: /registration/zfs.csi.openebs.io-reg.sock
I1111 05:31:24.480262       1 node_register.go:67] Registration Server started at: /registration/zfs.csi.openebs.io-reg.sock
I1111 05:31:24.981967       1 main.go:77] Received GetInfo call: &InfoRequest{}
I1111 05:31:25.982358       1 main.go:77] Received GetInfo call: &InfoRequest{}
I1111 05:31:26.003126       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

**Comment by dude051** [comment]
@pawanpraka1 correct that's the full log that I have. It just stops there with nothing else.

**Comment by pawanpraka1** [comment]
could you share the yaml you have used to deploy the operator?

**Comment by dude051** [comment]
only change I have made was for the location of kubelet:
https://gist.github.com/dude051/a960b6c0febf22729537e122c2dee831

**Comment by pawanpraka1** [comment]
can we change all the places where we have "/var/lib/kubelet" to '/var/snap/microk8s/common/var/lib/kubelet/" and deploy it again and see `kubectl get csinodes -oyaml` and check if spec.drivers is populated.

**Comment by dude051** [comment]
@pawanpraka1 thank you, that was it! I hadn't thought to go through and change the kubelet version everywhere after skimming it from the issue that I found, so totally my mistake there.

**Comment by dude051** [comment]
I see the node registered the driver now
```
spec:
  drivers:
  - name: zfs.csi.openebs.io
    nodeID: ubuntu
    topologyKeys:
    - beta.kubernetes.io/arch
    - beta.kubernetes.io/os
    - kubernetes.io/arch
    - kubernetes.io/hostname
    - kubernetes.io/os
    - microk8s.io/cluster
    - openebs.io/nodename
``` 
and my test PVC was provisioned and bound:
```
default     pihole-test-pvc   Bound    pvc-de359185-7774-44c1-b002-7a52244246ae   4Gi        RWO            openebs-zfs    2d3h
```

**Comment by pawanpraka1** [comment]
can we help us document this in the readme for microk8s?

**Comment by dude051** [comment]
Sure glad to write that up and submit.

**Comment by pawanpraka1** [comment]
Thanks @dude051

**Comment by Crespalvaro** [comment]
Im sorry to repoen this but as Im experiencing the same "exact" issue without being able to find a solution I guess I need your help.

I already worked with this project in k0s and everything went fine. Updated in [zfs-operator](https://openebs.github.io/charts/zfs-operator.yaml) k0s kubelet location and worker. Now, as k0s its not so good with hybrid clusters containing windows workers (to avoid openebs-zfs-node pods being created on windows nodes and attempting to schedule pvcs there I added a nodeSelector: linux on zfs-operator.yaml. I dont need to create pv in windows workers, only in linux), I switched to a different distribution. In this case its a custom baremetal rke1, rancher 2.6.2 with kubernetes 1.21.5.

This time I updated kubelet to rancher kubelet location /opt/rke/var/lib/kubelet/ and double checked that its true kubelet its installed there.

The first error I noticed while working in rke with zfs-localpv is the following error on scheduling PVCs.

**failed to provision volume with StorageClass "openebs-zfspv-retain": error generating accessibility requirements: no topology key found on CSINode kspdev01worker03**

As I added allowedTopologies to my storage classes to avoid PVCs and PVs being created on windows workers, my first thought was that the error was there.

allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - kspdev01worker01
      - kspdev01worker02
      - kspdev01worker03

However I deleted it and the same error persisted. Thus, I also updated defaul  zfs-operator.yaml _topologyKey: "kubernetes.io/hostname"_ to a custom label I added to my nodes, same issue. On a different issue here found another workaround deleting _"--feature-gates=Topology=true"_ and _"--strict-topology"_ flag. This time the error changed to:

**failed to provision volume with StorageClass "openebs-zfspv-retain": rpc error: code = Internal desc = scheduler failed, not able to select a node to create the PV**

My csi-node-driver-registrar logs:
`
I1027 17:42:16.849130 1 main.go:113] Version: v2.1.0
I1027 17:42:16.849585 1 main.go:137] Attempting to open a gRPC connection with: "/plugin/csi.sock"
I1027 17:42:16.849615 1 connection.go:153] Connecting to unix:///plugin/csi.sock
I1027 17:42:17.851692 1 main.go:144] Calling CSI driver to discover driver name
I1027 17:42:17.851773 1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I1027 17:42:17.851808 1 connection.go:183] GRPC request: {}
I1027 17:42:17.856039 1 connection.go:185] GRPC response: {"name":"zfs.csi.openebs.io","vendor_version":"1.5.0"}
I1027 17:42:17.856115 1 connection.go:186] GRPC error: <nil>
I1027 17:42:17.856123 1 main.go:154] CSI driver name: "zfs.csi.openebs.io"
I1027 17:42:17.856158 1 node_register.go:52] Starting Registration Server at: /registration/zfs.csi.openebs.io-reg.sock
I1027 17:42:17.856354 1 node_register.go:61] Registration Server started at: /registration/zfs.csi.openebs.io-reg.sock
I1027 17:42:17.856458 1 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
`

Finally here is my [rancher-zfs-operator.yaml](https://github.com/Crespalvaro/zfs-file/blob/master/rancher-provisioner-openebs-zfs.yaml)

**Edit**

I dont know how but I just noticed that I forgot to update:

- name: plugin-dir
          hostPath:
            path: /var/lib/k0s/kubelet/plugins/zfs-localpv/
            type: DirectoryOrCreate
- name: pods-mount-dir
          hostPath:
            path: /var/lib/k0s/kubelet/
            type: Directory

[updated-zfs-operator.yaml](https://github.com/Crespalvaro/zfs-file/blob/master/rancher-provisioner-openebs-zfs-updated.yaml)

Still I did changed it to rke kubelet location, and my drivers are still null. Also same error provisioning pvcs

**Comment by pawanpraka1** [comment]
@Crespalvaro  can you paste the openebs-zfs-plugin container log from the daemonset pod? Also I need the o/p of `kubectl get csinode -oyaml`.

**Comment by Crespalvaro** [comment]
@pawanpraka1 here is the plugin container log
[plugin-log.txt](https://github.com/openebs/zfs-localpv/files/7431614/plugin-log.txt)

Ouput from `kubectl get csinode -oyaml`:
[csinode.txt](https://github.com/openebs/zfs-localpv/files/7431629/csinode.txt)

**Comment by pawanpraka1** [comment]
@Crespalvaro it seems like driver registration is not happening. Can you delete all the csinodes CR and restart all the zfs node daemonset pods? 

Can you also share the o/p of this `kubectl get pods -n kube-system -l role=openebs-zfs -owide`.

**Comment by Crespalvaro** [comment]
@pawanpraka1 Yeah I thought about it but was not sure about deleting the csinodes as I didnt know where they come from.

After deleting
```
λ kubectl get csinodes -oyaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
```
kubectl get pods -n kube-system -l role=openebs-zfs -owide
NAME                       READY   STATUS    RESTARTS   AGE     IP                NODE               NOMINATED NODE   READINESS GATES
openebs-zfs-controller-0   5/5     Running   0          81s     10.42.3.27        kspdev01worker03   <none>           <none>
openebs-zfs-node-jcw2p     2/2     Running   0          5m31s   192.168.102.228   kspdev01worker03   <none>           <none>
openebs-zfs-node-jq8sb     2/2     Running   0          5m35s   192.168.102.226   kspdev01worker01   <none>           <none>
openebs-zfs-node-vxcql     2/2     Running   0          5m49s   192.168.102.227   kspdev01worker02   <none>           <none>
```

**Comment by cbrand** [comment]
Sorry for making yet another comment here but I did have the same issue with the `lvm-localpv` provisioner and this seems to be the issue which is one of the first search results:
What is imperative when doing this configuration is to not forget the `/` in the end of the kubelet path. 

Make sure that you use `/var/lib/k0s/kubelet/` instead of ~`/var/lib/k0s/kubelet`~ for the csi registraion to work.

So for example for k0s:
```yaml
zfs-localpv:
  enabled: true
  zfsNode:
    kubeletDir: "/var/lib/k0s/kubelet/"
```

And if you want to do lvm
```yaml
lvm-localpv:
  enabled: true
  lvmNode:
    kubeletDir: "/var/lib/k0s/kubelet/"
```
