### ISSUE TITLE
Latest operator yaml installs version 2.4.0 instead of the latest one

### ISSUE THREAD

**Issue by lord-kyron** [openebs/zfs-localpv#521]
After trying to re-deploy the operator with the latest version, I executed:
`$ kubectl apply -f https://openebs.github.io/charts/zfs-operator.yaml`
and then I realised, that the installed version was 2.4.0 instead of the current latest 2.5.0
I went inspecting the yaml file for the operator from the given URL and indeed, there the version 2.4.0 is present.

I guess the yaml is not updated with the latest version available.
Can you please, fix this? I know the latest version is available trough the helm chart, but there are some of us that don't want to use the helm.

**Comment by dave-brace** [comment]
Hi @lord-kyron ... we are currently in the run-down last few days of dropping a new release for the entire OpenEBS project.
v2.6 is coming in a few days (that's the current scheudle, assuming there are no more major Release blockers). 
Many release artifacts are being uploaded in real-time into the repos etc in preparation to enable the full release. OpenEBS is a very big project so its take a bit of time to get every lined up for a major drop across many Data-Engines etc.
You probably pulled down a yaml file that wasn't quite ready to be pushed, but got pushed live anyway (in prep for the release). These small errors have been happening a bit over the past few days. - Sorry about that 🙏🏼

**Comment by aep** [comment]
actually it looks like zfslocalpv will be dropped entirely? the instructions in the README now only contain a helm chart which installs unrelated things and is straight up broken.

Even if it did work, it's not clear how you would migrate given that the etcd is entirely separate now and the namespace changed and generally there are no docs. 

i was about to work on some bugfixes but it looks like it's not worth it?

**Comment by avishnu** [comment]
@aep ,
Can you check on the latest documentation for OpenEBS for install instructions?
https://openebs.io/docs/quickstart-guide/installation. 

LocalPV ZFS is definitely staying. If any documentation says otherwise, please let us know, we'll fix it.

OpenEBS did go through a considerable restructuring from v4.0 onwards. Please check https://github.com/openebs/openebs/releases for more information. 

Happy to help.

**Comment by orville-wright** [comment]
> actually it looks like zfslocalpv will be dropped entirely? the instructions in the README now only contain a helm chart which installs unrelated things and is straight up broken.
> 
> Even if it did work, it's not clear how you would migrate given that the etcd is entirely separate now and the namespace changed and generally there are no docs.
> 
> i was about to work on some bugfixes but it looks like it's not worth it?

@aep - not sure how you came to the assumption that "actually it looks like zfslocalpv will be dropped entirely?"

- This is defiantly NOT our strategy with **Local-PV ZFS**. 
- We are 100% committed to the **Local-PV ZFS** Storage Engine. 

Over the past few months, All Storage Engines have gone though major re-structuring. This is especially true with regard to HELM installation process becasue we are doing an extensive tidy-up of the LEGACY components of the entire openEBS project / product.

We designed a new project structure and a **Unified Helm installer** to reflect our new product structure, strategy & roadmap; which brings together,,,
1. Local PV <kbd>HostPath</kbd>
2. Local PV <kbd>ZFS</kbd>
3. Local PV <kbd>LVM2</kbd>
4. Replicated PV <kbd>Mayastor</kbd>
5. Local PV <kbd>(Rawfile*)</kbd>

- * (Rawfile is still under review and analysis)

These 5 main Storage Engines are now the entire focus on the **openEBS project** . 
- All other LEGACY components, repos, dependencies and artifacts have been migrated out to the openebs-archvie repo @ https://github.com/openebs-archive. All of this heavy re-structing & tidy-up has been done with help from CNCF **Exec Leadership**, CNCF **Technical Oversight Committee** (TOC), CNCF **Developer Relations** and CNCF **Storage Technical Advisory Group** (TAG). The Engineering work has been very complex and our new Unified HELM installer has gone through a lot of Eng/Dev iterations over a very short period. (yes Helm is quite a beast for complicated multi sub-project environments). Nevertheless, we love ```Local PV ZFS``` and were committed to its future.

So... **```Local PV ZFS```** (note: tidied up new name so that all products have well understood aligned names) is... absolutely 100% supported, and is a CORE part of openEBS' future. It's not going anywhere. Its actually getting a lot of focus and engineering effort.

Hope this helps.

~Dave
@orville-wright

**Comment by aep** [comment]
Thanks. 

The helm chart brings up an entirely new architecture that doesnt is not production ready. No snapshots, no live backups, its own etcd that doesnt work out of the box, no migration docs..

I tested zfs localpv 2.5.0 standalone and it seems to work just fine without any of the other stuff, so this is mostly just confusing if you've not followed the rest of openebs and all you want is upgrade zfslovalpv. I also opened a PR for fixing my issue.

Thanks to your response, i'm assuming  this is probably just a documentation issue. I'll try to dig into it and see if i can write a migration doc after figuring out how to disable all the extra stuff in the helm chart.

**Comment by avishnu** [comment]
Few clarifications:

The v4.0 OpenEBS helm chart is an integrated solution and intended to install all the below storage engines 'out-of-the-box' in it's default mode:

1. Local PV Hostpath
2. Local PV LVM
3. Local PV ZFS
4. Replicated PV Mayastor

We refer to this unified installer as 'umbrella' OpenEBS.
However, we have provided options to 'disable' Local PV LVM / Local PV ZFS / Replicated PV Mayastor during installation.
The stand-alone etcd is needed for Mayastor.

At the moment, we don't have live migration strategies for standalone users of Local PV ZFS to upgrade to Local PV ZFS from umbrella OpenEBS. However, capability-wise, there is no difference, it's all the same, as the umbrella OpenEBS helm chart uses the standalone chart as it's dependency.

So, the umbrella is production-ready and "No snapshots, no live backups," is not true.

**Comment by Abhinandan-Purkait** [comment]
@lord-kyron Operator based installation is deprecated now. The only supported installation way is helm based installation via the openebs umbrella chart. Please follow this document. https://openebs.io/docs/quickstart-guide/installation#installation-via-helm 

Closing this as the above issue is now out of scope. Please feel free to reopen.
